### ISSUE TITLE
Panels don't shade the whole UI

### ISSUE THREAD

**Issue by edwardloveall** [arcticicestudio/northem-light-atom-ui#1] opened 2016-10-11 20:49 UTC
Opening the [fuzzy finder](https://atom.io/packages/fuzzy-finder) (or any other panel) doesn't shade the cover the whole workspace. The shade only extends `1.5em` out from the edges of the fuzzy finder panel:

![fuzzy finder shade](https://cloud.githubusercontent.com/assets/49549/19287947/e7052464-8fd1-11e6-9258-578a8802c912.png)

After playing around in the console for a second, if you remove [this line](https://github.com/arcticicestudio/northem-light-atom-ui/blob/84dd24851679620f8eb55659e6417efb0e9039c6/styles/components/panels.less#L56) is shades correctly.

I believe this is because when a parent element has relative positioning (as panels do in this theme) children with absolute positioning are relative to their parent. Weird, right?

Anyway, would you be opposed to a PR to fix this?

**Comment by arcticicestudio** [comment] 2016-10-12 14:00
Thanks for your detailed report, this is really weird. Feel free to create a PR if you'd like to fix this, else I'll try to release a new version this weekend :smile: 
I also planned to do a general update for my Northem UI and Syntax themes to keep up with the latest Atom UI changes. Maybe this bug is caused by the new Pane API and/or layout API introduced in Atom 1.9, 1.10 and 1.11.
Sadly i've neglected my Northem themes due to my new [Nord](https://github.com/arcticicestudio/nord) themes which will also provide a light version in feature versions.

**Comment by edwardloveall** [comment] 2016-10-12 15:25
Done! Great to know about planned updates. The fashion is definitely leaning toward dark themes these days, but I still love bright ones.

**Comment by arcticicestudio** [comment] 2016-10-15 21:29
Merged your PR #2 into `develop` and will release a new version to APM tomorrow.
Anyway, I decided to use my new [Nord Atom UI](https://github.com/arcticicestudio/nord-atom-ui) theme as code base for my Northem Atom themes and adjust the colors of my Northem color palette to it. The Nord themes are up to date with the latest Atom changes and rewritten clean from scratch with a lot of improvements and features which would take too long to adapt into all my Northem themes.

I'll start the Northem rewrite as soon as I've implemented the custom theme settings for user feature for my Nord Atom UI theme which will include a option to switch to a bright Nord color style. This merge will mark the new code base for my Northem themes since then I only have to switch the color palettes :wink: 

I would really appreciate some feedback about this idea.
In the meantime you can check out my Nord Atom UI theme to see if you like the new style like e.g. the buttons, lists and so on.
That's what this theme than will be look like, but colored using my Northem palette and of of course with a bright/light style :smile:

**Comment by edwardloveall** [comment] 2016-10-16 15:55
Yeah I'll definitely check it out over the next couple of days. Is there a good place to give you feedback? I feel like github issue on a separate project isn't the place.

**Closed as completed** 2016-10-16 19:22 UTC

**Comment by arcticicestudio** [comment] 2016-10-16 19:28
I'll create a tracking issue as soon as I start working on the rewrite and a related branch which can be tested for feedback. I'll add a mention to you to get you notified :wink: 
Also released version `0.4.1` some moments ago with your fix applied :smile:
